// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwpphrdwnexqqnihwqik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3cHBocmR3bmV4cXFuaWh3cWlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDMxMTcsImV4cCI6MjA3MzE3OTExN30.ZJhJt22U1VgqHpv5Y1gdy-jfC-dQbJt6xHEgPfblYuQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});